ignore_patterns:
  - "**/*.jpg"
  - "**/*.png"
  - "**/*.gif"
  - "**/*.svg"

priority_rules:
  - score: 100
    pattern: "^sources/website/content/src/content/docs/docs/.*\\.mdx?$"

output_template: "> FILE_PATH\n\nFILE_CONTENT"
